SELECT
	 [COLLISION_ID] AS [Collision ID]
	,CAST([CRASH_DATE] AS date) AS [Crash Date] -- Drop time and purely present Date in YYYY-MM-DD format only
	,DATEPART(WEEKDAY, CRASH_DATE) AS [Day Key] -- Determined which day the accident took part
	,CASE WHEN DATEPART(WEEKDAY, CRASH_DATE) = 1 THEN 'Sun'  -- Convert day key into DDD format
          WHEN DATEPART(WEEKDAY, CRASH_DATE) = 2 THEN 'Mon'
		  WHEN DATEPART(WEEKDAY, CRASH_DATE) = 3 THEN 'Tue'
		  WHEN DATEPART(WEEKDAY, CRASH_DATE) = 4 THEN 'Wed'
		  WHEN DATEPART(WEEKDAY, CRASH_DATE) = 5 THEN 'Thu'
		  WHEN DATEPART(WEEKDAY, CRASH_DATE) = 6 THEN 'Fri'
		  WHEN DATEPART(WEEKDAY, CRASH_DATE) = 7 THEN 'Sat'
		  END 
		  AS Day

	,DATEPART(MONTH, CRASH_DATE) AS [Month Key]  -- Created separate column for month
	,CASE WHEN DATEPART(MONTH, CRASH_DATE) = 1 THEN 'Jan'  -- Convert month key into MMM format
		  WHEN DATEPART(MONTH, CRASH_DATE) = 2 THEN 'Feb'
		  WHEN DATEPART(MONTH, CRASH_DATE) = 3 THEN 'Mar'
		  WHEN DATEPART(MONTH, CRASH_DATE) = 4 THEN 'Apr'
		  WHEN DATEPART(MONTH, CRASH_DATE) = 5 THEN 'May'
		  WHEN DATEPART(MONTH, CRASH_DATE) = 6 THEN 'Jun'
		  WHEN DATEPART(MONTH, CRASH_DATE) = 7 THEN 'Jul'
		  WHEN DATEPART(MONTH, CRASH_DATE) = 8 THEN 'Aug'
		  WHEN DATEPART(MONTH, CRASH_DATE) = 9 THEN 'Sep'
		  WHEN DATEPART(MONTH, CRASH_DATE) = 10 THEN 'Oct'
		  WHEN DATEPART(MONTH, CRASH_DATE) = 11 THEN 'Nov'
		  WHEN DATEPART(MONTH, CRASH_DATE) = 12 THEN 'Dec'
		  END 
		  AS Month
	  
	  ,DATEPART(YEAR, CRASH_DATE) AS [Year]
	  ,[CRASH_TIME] AS [Time]
	  ,CASE WHEN [CRASH_TIME] BETWEEN '00:00:00' AND '01:00:00' THEN '12 MN - 1 AM' 
			WHEN [CRASH_TIME] BETWEEN '01:00:00' AND '02:00:00' THEN '1 - 2 AM'
			WHEN [CRASH_TIME] BETWEEN '02:00:00' AND '03:00:00' THEN '2 - 3 AM'
			WHEN [CRASH_TIME] BETWEEN '03:00:00' AND '04:00:00' THEN '3 - 4 AM'
			WHEN [CRASH_TIME] BETWEEN '04:00:00' AND '05:00:00' THEN '4 - 5 AM'
			WHEN [CRASH_TIME] BETWEEN '05:00:00' AND '06:00:00' THEN '5 - 6 AM'
			WHEN [CRASH_TIME] BETWEEN '06:00:00' AND '07:00:00' THEN '6 - 7 AM'
			WHEN [CRASH_TIME] BETWEEN '07:00:00' AND '08:00:00' THEN '7 - 8 AM'
			WHEN [CRASH_TIME] BETWEEN '08:00:00' AND '09:00:00' THEN '8 - 9 AM'
			WHEN [CRASH_TIME] BETWEEN '09:00:00' AND '10:00:00' THEN '9 - 10 AM'
			WHEN [CRASH_TIME] BETWEEN '10:00:00' AND '11:00:00' THEN '10 - 11 AM'
			WHEN [CRASH_TIME] BETWEEN '11:00:00' AND '12:00:00' THEN '11 AM - 12 NN'
			WHEN [CRASH_TIME] BETWEEN '12:00:00' AND '13:00:00' THEN '12 - 1 NN' 
			WHEN [CRASH_TIME] BETWEEN '13:00:00' AND '14:00:00' THEN '1 - 2 PM'
			WHEN [CRASH_TIME] BETWEEN '14:00:00' AND '15:00:00' THEN '2 - 3 PM'
			WHEN [CRASH_TIME] BETWEEN '15:00:00' AND '16:00:00' THEN '3 - 4 PM'
			WHEN [CRASH_TIME] BETWEEN '16:00:00' AND '17:00:00' THEN '4 - 5 PM'
			WHEN [CRASH_TIME] BETWEEN '17:00:00' AND '18:00:00' THEN '5 - 6 PM' 			
			WHEN [CRASH_TIME] BETWEEN '18:00:00' AND '19:00:00' THEN '6 - 7 PM'
			WHEN [CRASH_TIME] BETWEEN '19:00:00' AND '20:00:00' THEN '7 - 8 PM' 
			WHEN [CRASH_TIME] BETWEEN '20:00:00' AND '21:00:00' THEN '8 - 9 PM'
			WHEN [CRASH_TIME] BETWEEN '21:00:00' AND '22:00:00' THEN '9 - 10 PM'
			WHEN [CRASH_TIME] BETWEEN '22:00:00' AND '23:00:00' THEN '10 - 11 PM'  
			WHEN [CRASH_TIME] BETWEEN '23:00:00' AND '23:59:59.99' THEN '11 PM - 12 MN' END AS [Time Group]
      ,[BOROUGH] AS [Town]
      ,[ZIP_CODE] AS [Zip Code]
      ,[LATITUDE] AS [Latitude]
      ,[LONGITUDE] AS [Longitude]
      --,[LOCATION]
      ,[ON_STREET_NAME] AS [Street]
      ,[CROSS_STREET_NAME] AS [Crossing Street]
      ,[OFF_STREET_NAME] AS [Off Street]
      ,[NUMBER_OF_PERSONS_INJURED] AS [Injured Persons]
      ,[NUMBER_OF_PERSONS_KILLED] AS [Killed Persons]
      ,[NUMBER_OF_PEDESTRIANS_INJURED] AS [Injured Pedestrians]
      ,[NUMBER_OF_PEDESTRIANS_KILLED] AS [Killed Pedestrians]
      ,[NUMBER_OF_CYCLIST_INJURED] AS [Injured Cyclists]
      ,[NUMBER_OF_CYCLIST_KILLED] AS [Killed Cyclists]
      ,[NUMBER_OF_MOTORIST_INJURED] AS [Injured Motorists]
      ,[NUMBER_OF_MOTORIST_KILLED] AS [Killed Motorists]
      ,[CONTRIBUTING_FACTOR_VEHICLE_1] AS [Contributing Factor - Vehicle 1]
      ,[CONTRIBUTING_FACTOR_VEHICLE_2] AS [Contributing Factor - Vehicle 2]
      ,[CONTRIBUTING_FACTOR_VEHICLE_3] AS [Contributing Factor - Vehicle 3]
      ,[CONTRIBUTING_FACTOR_VEHICLE_4] AS [Contributing Factor - Vehicle 4]
      ,[CONTRIBUTING_FACTOR_VEHICLE_5] AS [Contributing Factor - Vehicle 6]
      ,[VEHICLE_TYPE_CODE_1] AS [Vehicle 1]
      ,[VEHICLE_TYPE_CODE_2] AS [Vehicle 2]
      ,[VEHICLE_TYPE_CODE_3] AS [Vehicle 3]
      ,[VEHICLE_TYPE_CODE_4] AS [Vehicle 4]
      ,[VEHICLE_TYPE_CODE_5] AS [Vehicle 5]
FROM NYC_Accidents..nyc_car_accidents
WHERE [CRASH_DATE] < '01/01/2023'  -- Only include data up to 2022 as records for 2023 are still being collected


